# Rust 代码格式化配置
# https://rust-lang.github.io/rustfmt/

# 基本配置
edition = "2024"
max_width = 100
hard_tabs = false
tab_spaces = 4

# 导入排序
reorder_imports = true
group_imports = "StdExternalCrate"

# 函数和结构体格式化
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
indent_style = "Block"

# 注释和字符串
wrap_comments = true
format_code_in_doc_comments = true
format_strings = false

# 结构体和枚举
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0

# 链式调用
chain_width = 60
single_line_if_else_max_width = 50

# 空格和换行
spaces_around_ranges = false
trailing_comma = "Vertical"
trailing_semicolon = true
use_small_heuristics = "Default"

# 属性格式化
overflow_delimited_expr = false
struct_lit_single_line = true
fn_single_line = false
where_single_line = false

# 宏格式化
format_macro_matchers = true
format_macro_bodies = true

# 字符串和注释
normalize_comments = false
normalize_doc_attributes = false

# 实验性功能（需要 nightly）
# format_generated_files = false
# skip_macro_invocations = []
