# Rust 代码格式化配置
# https://rust-lang.github.io/rustfmt/

# 基本配置
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
reorder_imports = true
chain_width = 60
single_line_if_else_max_width = 50
use_small_heuristics = "Default"
