# PowerShell post hook for cargo-generate

$project = "{{project-name}}"

Write-Output ""
Write-Output "🎉 Project $project created successfully!"
Write-Output ""
Write-Output "📁 Project structure:"
Write-Output "   ├── src/          # Source code"
Write-Output "   ├── tests/        # Integration tests"
Write-Output "   ├── examples/     # Example code"
Write-Output "   └── assets/       # Static assets"
Write-Output ""
Write-Output "🚀 Next steps:"
Write-Output "   1. cd $project"
Write-Output "   2. cargo check     # Verify compilation"
Write-Output "   3. cargo test      # Run tests"
Write-Output "   4. cargo run       # Run the project"
Write-Output ""
Write-Output "🔧 Optional setup:"
Write-Output "   - git init && git add . && git commit -m \"Initial commit\""
Write-Output "   - pre-commit install  # Setup pre-commit hooks"
Write-Output "   - cargo doc --open    # Generate and view docs"
Write-Output ""
Write-Output "📚 Learn more: https://doc.rust-lang.org/book/"
